AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  Sample SAM Template for hnap_json_harvest

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HnapJsonHarvestFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Events:
        HnapJsonHarvest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hnap_json_harvest
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./hnap_json_harvest
      DockerTag: python3.8-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HnapJsonHarvestApi:
    Description: "API Gateway endpoint URL for Prod stage for HNAP JSON Harvesting function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hnap_json_harvest/"
  HnapJsonHarvestFunction:
    Description: "HNAP JSON Harvesting Lambda Function ARN"
    Value: !GetAtt HnapJsonHarvestFunction.Arn
  HnapJsonHarvestFunctionIamRole:
    Description: "Implicit IAM Role created for HNAP JSON Harvesting function"
    Value: !GetAtt HnapJsonHarvestFunctionRole.Arn
